const products = [
  {
    _id: '1',
    imageUrl: '/assets/cyberpunk1.jpg',
    category: 'RPG',
    title: 'Cyberpunk',
    subtitle: '2077',
    price: '$82',
    earlierPrice: '$108',
  },
  {
    _id: '2',
    imageUrl: '/assets/fifa21.jpg',
    category: 'Sport',
    title: 'FIFA 21',
    subtitle: 'EA SPORTS',
    price: '$75',
    earlierPrice: '$99',
  },
  {
    _id: '3',
    imageUrl: '/assets/assasin.jpg',
    category: 'RPG',
    title: `Assassin's Creed`,
    subtitle: 'Vallhalla',
    price: '$69',
    earlierPrice: '$93',
  },
  {
    _id: '4',
    imageUrl: '/assets/callofduty.jpg',
    category: 'FPS',
    title: 'Call of Duty',
    subtitle: 'Black Ops',
    price: '$73',
    earlierPrice: '$102',
  },
  {
    _id: '5',
    imageUrl: '/assets/ageofempires.jpg',
    category: 'Strategy',
    title: `Age of Emipres III`,
    subtitle: 'Definitive Edition',
    price: '$69',
    earlierPrice: '$93',
  },
  {
    _id: '6',
    imageUrl: '/assets/immortalsfenyxrising.jpg',
    category: 'Action',
    title: 'Immortals',
    subtitle: 'Fenyx Rising',
    price: '$73',
    earlierPrice: '$102',
  },
  {
    _id: '7',
    imageUrl: '/assets/sims4.jpg',
    category: 'Simulator',
    title: 'The Sims 4',
    subtitle: 'Eco Lifestyle',
    price: '$69',
    earlierPrice: '$93',
  },
  {
    _id: '8',
    imageUrl: '/assets/diablo2.jpg',
    category: 'RPG',
    title: 'Diablo 2',
    subtitle: 'Expansion Set',
    price: '$73',
    earlierPrice: '$102',
  },
  {
    _id: '9',
    imageUrl: '/assets/avengers.jpg',
    category: 'Action',
    title: `Marvel's Avengers`,
    subtitle: 'Infinity War',
    price: '$69',
    earlierPrice: '$93',
  },
  {
    _id: '10',
    imageUrl: '/assets/flight.jpg',
    title: 'Call of Duty',
    subtitle: 'Black Ops',
    price: '$73',
    earlierPrice: '$102',
  },
  {
    _id: '11',
    imageUrl: '/assets/rocketleague.jpg',
    category: 'Sport',
    title: `Rocket League`,
    subtitle: 'Sport Game',
    price: '$69',
    earlierPrice: '$93',
  },
  {
    _id: '12',
    imageUrl: '/assets/doom.jpg',
    category: 'FPS',
    title: 'Doom',
    subtitle: 'Eternal',
    price: '$73',
    earlierPrice: '$102',
  },
];

export default products;